### ISSUE TITLE
document all options in BIDScramble

### ISSUE THREAD

**Issue by robertoostenveld** [SIESTA-eu/wp15#33]
I noticed that there are options which are not completely documented, like the --preserve option for the tsv action and the --select option for the pseudo action. Since they seem to have subtle differences between the actions, I don't dare to document them myself. 

@marcelzwiers can you go over the code, update the command-line help, and update the overall README?

**Comment by robertoostenveld** [comment]
the --bidsvalidate also seems to be not consistently documented over all actions

**Comment by robertoostenveld** [comment]
Hi Marcel, have all current options been documented?

**Comment by marcelzwiers** [comment]
I updated the docs (i.e. I manually pasted the output of `scramble in out [action] -h`) in the markdown file, and added sections for your fif and brainvision actions. Ideally, these markdown sections are autogenerated from the argparse code (I don't know how to do this, but I've seen other projects do it). I didn't really add much new documentation, because I think the scramble command line tool help texts were just fine
