### ISSUE TITLE
memory size limit

### ISSUE THREAD

**Issue by Marque-CerCo** [SIESTA-eu/wp15#35]
Hello,
I complete the information on use case 2.5. I propose a modified version of spm12 (without the interactive part asking users to enter input). However, the size exceeds the memory limit. Is it possible to get around this limit? Do I need to provide a link to download this version of spm12 using the wget command?
Thank you in advance for your reply.
Marque Adrien

**Comment by robertoostenveld** [comment]
Hi Adrien,  

The idea of the https://github.com/SIESTA-eu/wp15 repository is only to contain the code that you wrote for the specific analysis, not the complete software on which it depends. The dependencies are listed in the documentation, including installation instructions (which could include wget commands).

Since you write that you need a modified version of SPM12, I suggest that you make a fork of https://github.com/spm/spm12 to your personal https://github.com/Marque-CerCo account on GitHub and that in that fork you make a branch, and that in that branch you implement the required changes.

The README documentation in usecase-2.5 should then explain that the spm12 version is to be obtained from that specific branch of the https://github.com/Marque-CerCo/spm12 repository. 

I hope this is clear. Please do get started by sharing the analysis pipeline in the usecase-2.5 folder so that we (including @schoffelen and @marcelzwiers) can see what you have in mind. The first version does not have to be perfect and does not even have to run completely. Better that awe can see what errors it gives so that we can help you to document the fix.

best regards,
Robert

**Comment by robertoostenveld** [comment]
Hi Adrien, any progress here? Is there a way that I can help?

**Comment by schoffelen** [comment]
> Hello, I complete the information on use case 2.5. I propose a modified version of spm12 (without the interactive part asking users to enter input). However, the size exceeds the memory limit. Is it possible to get around this limit? Do I need to provide a link to download this version of spm12 using the wget command? Thank you in advance for your reply. Marque Adrien

Hi Adrien @Marque-CerCo can I think along perhaps with the SPM12 size issue you are facing? I was just wondering during the wp15 zoom meeting why you need to upload that much code into github? Specifically, you mention that you don't need the interactive features of SPM (which is great!) but perhaps we can figure out a workaround that wouldn't require you to modify so much of the SPM code in order to get your pipelines running non-interactively. More specifically, I often interact with SPM without using the interactive user environment to begin with, just by calling the respective non-interactive lower-level functions directly. This I even occasionally do to run a full (first-level) pipeline that fits GLMs to individual subjects. Please feel free to reach out if you want to discuss this.
